### ISSUE TITLE
클론코딩 주제 정하기

### ISSUE THREAD

**Issue by jungyoun** [G01K/reactStudy#1]
클론코딩 어떤거 할껀지 의견주세요.

**Comment by G01K** [comment]
1. 포트폴리오
   1. 개인 인적사항
   2. 경력
   3. 프로젝트
   4. 사용가능한 스킬별 숙련도

**Comment by leeedev** [comment]
노트와 같은 간단한 서비스나, 넷플릭스나, 인스타그램 등도 좋을 것 같습니다 👍

**Comment by BoMeeYoon** [comment]
인스타그램 클론도 좋을 것 같습니다 =)

**Comment by jungyoun** [comment]
넷플릭스는 그럼 영상이 플레이 되는것까지 코딩하는거에요?

**Comment by jungyoun** [comment]
그럼 주제는 넷플릭스 하는것으로 결정하고 이슈 종료합니다.
