### ISSUE TITLE
스터디 일정/방식 정하기

### ISSUE THREAD

**Issue by jungyoun** [G01K/reactStudy#2]
이미 나온 의견
- 2주에 1번
- 장소는 강남 괜찮음
- 주말 괜찮음

자유롭게 의견주세요~

**Comment by jungyoun** [comment]
https://grapelounge.co.kr/gangnam_branch 장소

**Comment by wandukong** [comment]
스터디 장소 : 그레이프라운지 강남점 ( https://grapelounge.co.kr/gangnam_branch )
다음 장소는 여기가 될거 같습니다~
